import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { motion } from "framer-motion";
import { ThemeProvider } from "../components/ThemeProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <NextAuthProvider> */}
        <div className="bg-white text-black dark:bg-gray-900 dark:text-white">
          <ThemeProvider>{children}</ThemeProvider>
        </div>
        {/* {children} */}
        {/* </NextAuthProvider> */}
      </body>
    </html>
  );
}
